### ISSUE TITLE
nightmode background

### ISSUE THREAD

**Issue by HarrisonSK** [kawf/kawf#22]
In nightmode, the background tag inherited from html is coming over and not being overwritten with a code appropriate for nightmode.

```
body, html {
  font-family: Roboto, Verdana, Arial, Geneva, sans-serif;
  font-size: 0.96em;
  font-weight: normal; /* 400 */
  background: #fff;
  color: #242424;
```

#fff should be #1a1a1d.

Thanks!

**Comment by nyetwurk** [comment]
For which element?

**Comment by HarrisonSK** [comment]
When I inspect the page in Chrome, I am able to see it this way:

![image](https://cloud.githubusercontent.com/assets/23173245/19865402/4e4316c2-9f59-11e6-8312-a1ae81f7f0f5.png)


![image](https://cloud.githubusercontent.com/assets/23173245/19865427/6ab7b5a6-9f59-11e6-8ef8-e7f1d2315dbd.png)

You can see the white boarder around the content on the first screenshot, but not the second?  This is MUCH more apparent when you look at an actual message and it doesn't fill the entire screen.

![image](https://cloud.githubusercontent.com/assets/23173245/19865565/03413d24-9f5a-11e6-999e-2df456249bd7.png)


I hope this makes sense?

**Comment by nyetwurk** [comment]
Yes, it does, thank you!
I see the issue.
