### ISSUE TITLE
Embeded YouTube videos do not acknowledge time reference

### ISSUE THREAD

**Issue by HarrisonSK** [kawf/kawf#29]
embedded youtube vidoes do not acknowledge the time reference after the video url.

e.g. https://youtu.be/llyiQ4I-mcQ?t=54s

after the YouTube Video ID (/llyiQ4I-mcQ) a time reference is called (?=54s), but is ignored once embedded.

**Comment by nyetwurk** [comment]
09ade12706243ed78243fd02811f01292cb1a413
