### ISSUE TITLE
Automatically generate SCHEMA_VERSION in user/tables.inc

### ISSUE THREAD

**Issue by nyetwurk** [kawf/kawf#47]
Currently, SCHEMA_VERSION in user/tables.inc has to be edited every time a new migration is added to migrations so that new installs automatically get tagged with the latest MIGRATION version.

This is easily overlooked. It should be automatically figured out based on the contents of the migrations directory.

**Comment by complacentsee** [comment]
Is your intention that the SCHEMA_VERSION would be updated as part of a make or automatically derived during the initial.php execution? 
It should be easy to implement the latter by borrowing some of the logic from migrations.inc to implement a new method get_latest_schema_version. Then call get_latest_schema_version and update_schema_version during initial.php.

**Comment by complacentsee** [comment]
This is a first attempt at this. https://github.com/complacentsee/kawf/commit/802ea446fbf87e3673ed559d8af308aa46ce73b9
