### ISSUE TITLE
Make a "disable admin" mode so you can browse as admin w/o fear of fat fingering

### ISSUE THREAD

**Issue by nyetwurk** [kawf/kawf#51]
The various admin button (delete offtopic etc) are too easy to hit, especially when browsing via mobile.

Need to add some client side JS toggle (like night mode) to disable the admin buttons for safer browsing.

**Comment by complacentsee** [comment]
I think this is a cleaner method. 
https://github.com/complacentsee/kawf/commit/362d3935f10b0b63da6f8c23d84e6c1a6be42177
