### ISSUE TITLE
Sometimes a thread goes missing between page 1 and page 2

### ISSUE THREAD

**Issue by nyetwurk** [kawf/kawf#62]
Sometimes a thread goes missing between page 1 and page 2, in particular, if there are both deleted threads in page 1 and stickies(?)

**Comment by complacentsee** [comment]
This should be corrected with with https://github.com/kawf/kawf/commit/fbd19d520f644c87b8258bbd346fd60d3ac669e6 which makes pages > 1 aware of how many threads were stuck and adjust thread select limits accordingly.
